In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv('SUV_Car.csv')

In [3]:
print(data)

    Gender  Age  EstimatedSalary  Purchased
0     Male   19            19000          0
1     Male   35            20000          0
2   Female   26            43000          0
3   Female   27            57000          0
4     Male   19            76000          0
5     Male   27            58000          0
6   Female   27            84000          0
7   Female   32           150000          1
8     Male   25            33000          0
9   Female   35            65000          0
10  Female   26            80000          0
11  Female   26            52000          0
12    Male   20            86000          0
13    Male   32            18000          0
14    Male   18            82000          0
15    Male   29            80000          0
16    Male   47            25000          1
17    Male   45            26000          1
18    Male   46            28000          1
19  Female   48            29000          1
20    Male   45            22000          1
21  Female   47            49000

In [4]:
data['Gender'] = data['Gender'].replace('Female',0)
data['Gender'] = data['Gender'].replace('Male',1)
print(data)

    Gender  Age  EstimatedSalary  Purchased
0        1   19            19000          0
1        1   35            20000          0
2        0   26            43000          0
3        0   27            57000          0
4        1   19            76000          0
5        1   27            58000          0
6        0   27            84000          0
7        0   32           150000          1
8        1   25            33000          0
9        0   35            65000          0
10       0   26            80000          0
11       0   26            52000          0
12       1   20            86000          0
13       1   32            18000          0
14       1   18            82000          0
15       1   29            80000          0
16       1   47            25000          1
17       1   45            26000          1
18       1   46            28000          1
19       0   48            29000          1
20       1   45            22000          1
21       0   47            49000

In [5]:
x = np.ones(len(data)*(len(data.keys())))
x = x.reshape(len(data),len(data.keys()))

In [6]:
print(x)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [7]:
m = max(data['EstimatedSalary'])
for d in data.iterrows():
    x[d[0]][1] = d[1][0]
    x[d[0]][2] = d[1][1]
    x[d[0]][3] = d[1][2]/m
print(x, type(x[0][0]))

[[ 1.          1.         19.          0.12666667]
 [ 1.          1.         35.          0.13333333]
 [ 1.          0.         26.          0.28666667]
 [ 1.          0.         27.          0.38      ]
 [ 1.          1.         19.          0.50666667]
 [ 1.          1.         27.          0.38666667]
 [ 1.          0.         27.          0.56      ]
 [ 1.          0.         32.          1.        ]
 [ 1.          1.         25.          0.22      ]
 [ 1.          0.         35.          0.43333333]
 [ 1.          0.         26.          0.53333333]
 [ 1.          0.         26.          0.34666667]
 [ 1.          1.         20.          0.57333333]
 [ 1.          1.         32.          0.12      ]
 [ 1.          1.         18.          0.54666667]
 [ 1.          1.         29.          0.53333333]
 [ 1.          1.         47.          0.16666667]
 [ 1.          1.         45.          0.17333333]
 [ 1.          1.         46.          0.18666667]
 [ 1.          0.         48.  

In [8]:
y = data['Purchased']
w = np.ones(4)

In [9]:
def costFunction(x,y,w):
    m = len(x)
    mat = np.matmul(x,w)
    mat = np.subtract(mat,y)
    # J = np.matmul(mat.transpose(),mat)/m
    # print(mat)
    # print(np.exp((-1)*mat))
    J = 1/(1 + np.exp((-1)*mat))
    return sum(J)
costFunction(x,y,w)

21.99999999751831

In [10]:
def gradient(x,y,w,learning_rate,iterations=10000,stoping_threshold=0.000000000001):
    prev_cost = None
    bol = True
    for i in range(iterations):
        crnt_cost = costFunction(x,y,w)
        # print(crnt_cost)
        if prev_cost is not None and abs(prev_cost - crnt_cost) <= stoping_threshold:
            break
        m = len(x)
        prev_cost = crnt_cost
        mat = np.matmul(x,w)
        u = 1/(1 + np.exp((-1)*mat))
        # print(u)
        u = [1 if i >= 0.5 else 0 for i in u]
        # print(u)
        derivative = np.subtract(u, y)
        w[0] = w[0] - learning_rate*sum(derivative)
        w[1] = w[1] - learning_rate*np.matmul(x[:,1],derivative)
        w[2] = w[2] - learning_rate*np.matmul(x[:,2],derivative)
        w[3] = w[3] - learning_rate*np.matmul(x[:,3],derivative)
        # print(w)
    print(i)
    print(crnt_cost)
    return w

In [11]:
b = gradient(x,y,w,0.001)

9999
5.609621406195408


In [12]:
print(b)

[-9.942      -2.085       0.334      -1.47016667]


In [13]:
output = [b[0] + i[1]*b[1] + i[2]*b[2] + i[3]*b[3] for i in x]
print(output)
val = [1/(1 + np.exp((-1)*asdf)) for asdf in output]
print(val)
output = [1 if i >= 0.5 else 0 for i in val]
for i in range(len(output)):
    print(y[i],output[i])

[-5.867221111111375, -0.5330222222225629, -1.6794477777781278, -1.4826633333336368, -6.425884444444495, -3.577464444444603, -1.7472933333335359, -0.7241666666666473, -4.000436666666909, 1.110927777777464, -2.0420888888891007, -1.7676577777780942, -6.189895555555574, -1.5154200000003328, -6.818691111111134, -3.1250888888889747, 3.4259722222218407, 2.748171111110743, 3.0625688888885225, 5.805767777777264, 2.7873755555551725, 5.2757455555551225]
[0.0028227382886179273, 0.369812278949542, 0.15716860605701385, 0.1850254755200938, 0.001616483390620118, 0.027186696176214643, 0.14838891311680524, 0.32647611525929315, 0.017978498870188986, 0.7523020374327656, 0.11485419902480941, 0.145833849021133, 0.002045846787969985, 0.1801369380636155, 0.0010919571254309223, 0.04208414438582821, 0.9685064451982394, 0.9398099779103206, 0.9553220701221993, 0.9969988910214771, 0.9419897981538933, 0.9949118789662816]
0 0
0 0
0 0
0 0
0 0
0 0
0 0
1 0
0 0
0 1
0 0
0 0
0 0
0 0
0 0
0 0
1 1
1 1
1 1
1 1
1 1
1 1


In [14]:
def confusion(x,yy):
    confmat = np.array([0,0,0,0])
    confmat = confmat.reshape(2,2)
    for i in range(len(x)):
        out = b[0] + x[i][1]*b[1] + x[i][2]*b[2] + x[i][3]*b[3]
        out = 1/(1 + np.exp((-1)*out))
        if out >= 0.5:
            predy = 1
        else:
            predy = 0
        y = yy[i]
        if y == predy:
            if y == 0:
                confmat[0][0] += 1
            else:
                confmat[1][1] += 1
        else:
            if y == 0:
                confmat[1][0] += 1
            else:
                confmat[0][1] += 1
    return confmat

In [15]:
confusion(x,y)

array([[14,  1],
       [ 1,  6]])

In [16]:
def accuracy(mat):
    return (mat[0][0] + mat[1][1])/(mat[0][0] + mat[0][1] + mat[1][0] + mat[1][1])
def precision(mat):
    return (mat[0][0])/(mat[0][0] + mat[1][0])
def recall(mat):
    return (mat[0][0])/(mat[0][0] + mat[0][1])
def F1Score(p,r):
    return (2*(p*r))/(p + r)

In [17]:
mat = confusion(x,y) 
acc = accuracy(mat)
pre = precision(mat)
rec = recall(mat)
fscore = F1Score(pre, rec)
print(acc, pre, rec, fscore)

0.9090909090909091 0.9333333333333333 0.9333333333333333 0.9333333333333333
